name: break_in
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  get_it: ^7.2.0
  go_router: ^6.0.6
  hive: ^2.2.3
  http: ^0.13.5
  json_annotation: ^4.8.0
  path_provider: ^2.0.13
  provider: ^6.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.9
  image_picker: ^0.8.7
  mime: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
    - family: Urbanist_Bold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
    - family: Urbanist_Medium
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
    - family: Urbanist_Light
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
    - family: Urbanist_SemiBold
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
